export const ADD_LIST_MOVIES = 'ADD_LIST_MOVIES';
export const REMOVE_LIST_MOVIES = 'REMOVE_LIST_MOVIES';

export const SEARCH_START = 'START_SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';