export const SET_API_CONFIGURATION = 'SET_API_CONFIGURATION';

export const SET_LIST_MOVIES = 'SET_LIST_MOVIES';
export const ADD_LIST_MOVIES = 'ADD_LIST_MOVIES';
export const REMOVE_LIST_MOVIES = 'REMOVE_LIST_MOVIES';